blank_issues_enabled: false
contact_links:
  - name: pret Discord
    url: https://discord.gg/d5dubZ3
    about: If you need help with using pokecrystal, or just have general questions about it, ask in our Discord server!
