name: CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Checkout rgbds
        uses: actions/checkout@master
        with:
          path: rgbds
          ref: v1.0.1
          repository: gbdev/rgbds

      - name: Install rgbds
        working-directory: rgbds
        run: |
          sudo apt update
          sudo apt install -yq bison libpng-dev pkg-config
          sudo make -j$(nproc) install

      - name: Remove rgbds
        run: |
          rm -rf rgbds

      - name: Compare
        if: ${{ github.repository_owner == 'pret' }}
        run: |
          make DEBUG=1 -j$(nproc) compare
          .github/checkdiff.sh

      - name: Make
        if: ${{ github.repository_owner != 'pret' }}
        run: |
          make -j$(nproc)
          .github/checkdiff.sh

      - name: Discord webhook
        if: ${{ github.event_name == 'push' && github.repository_owner == 'pret' }}
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          .github/webhook.sh

      - name: Checkout symbols
        if: ${{ github.event_name == 'push' && github.repository_owner == 'pret' }}
        uses: actions/checkout@master
        with:
          path: symbols
          ref: symbols

      - name: Move symbols
        if: ${{ github.event_name == 'push' && github.repository_owner == 'pret' }}
        run: |
          cp -v *.sym symbols/
          cp -v *.map symbols/

      - name: Update symbols
        if: ${{ github.event_name == 'push' && github.repository_owner == 'pret' }}
        uses: EndBug/add-and-commit@v9
        with:
          cwd: "./symbols"
          add: "*.sym *.map"
          message: ${{ github.event.commits[0].message }}

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Checkout rgbds
        uses: actions/checkout@master
        with:
          path: rgbds
          ref: v1.0.1
          repository: gbdev/rgbds

      - name: Install rgbds
        working-directory: rgbds
        run: |
          brew install bison libpng pkg-config
          export PATH="$(brew --prefix bison)/bin:$PATH"
          sudo make -j$(sysctl -n hw.ncpu) install

      - name: Remove rgbds
        run: |
          rm -rf rgbds

      - name: Compare
        if: ${{ github.repository_owner == 'pret' }}
        run: |
          make DEBUG=1 -j$(sysctl -n hw.ncpu) compare
          .github/checkdiff.sh

      - name: Make
        if: ${{ github.repository_owner != 'pret' }}
        run: |
          make -j$(sysctl -n hw.ncpu)
          .github/checkdiff.sh
