name: CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set build jobs
        id: jobs
        shell: bash
        run: |
          if [[ "${RUNNER_OS}" == "macOS" ]]; then
            echo "make_jobs=$(sysctl -n hw.ncpu)" >> "$GITHUB_OUTPUT"
          else
            echo "make_jobs=$(nproc)" >> "$GITHUB_OUTPUT"
          fi

      - name: Checkout rgbds
        uses: actions/checkout@master
        with:
          path: rgbds
          ref: v1.0.1
          repository: gbdev/rgbds

      - name: Install rgbds
        working-directory: rgbds
        shell: bash
        run: |
          if [[ "${RUNNER_OS}" == "Linux" ]]; then
            sudo apt-get update
            sudo apt-get install -yq libpng-dev
          else
            brew install libpng pkg-config
          fi
          sudo make install

      - name: Remove rgbds
        run: |
          rm -rf rgbds

      - name: Compare
        if: ${{ github.repository_owner == 'pret' }}
        run: |
          make DEBUG=1 -j${{ steps.jobs.outputs.make_jobs }} compare
          if ! git diff-index --quiet HEAD --; then
            echo 'Uncommitted changes detected:'
            git diff-index HEAD --
            return 1
          fi

      - name: Make
        if: ${{ github.repository_owner != 'pret' }}
        run: |
          make -j${{ steps.jobs.outputs.make_jobs }}
          if ! git diff-index --quiet HEAD --; then
            echo 'Uncommitted changes detected:'
            git diff-index HEAD --
            return 1
          fi

      - name: Discord webhook
        if: ${{ github.event_name == 'push' && github.repository_owner == 'pret' }}
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          .github/webhook.sh

      - name: Checkout symbols
        if: ${{ github.event_name == 'push' && github.repository_owner == 'pret' }}
        uses: actions/checkout@master
        with:
          path: symbols
          ref: symbols

      - name: Move symbols
        if: ${{ github.event_name == 'push' && github.repository_owner == 'pret' }}
        run: |
          cp -v *.sym symbols/
          cp -v *.map symbols/

      - name: Update symbols
        if: ${{ github.event_name == 'push' && github.repository_owner == 'pret' }}
        uses: EndBug/add-and-commit@v9
        with:
          cwd: "./symbols"
          add: "*.sym *.map"
          message: ${{ github.event.commits[0].message }}
